// Generated map of every mdi-* icon name used in the app to its @mdi/js SVG path.
import {
  mdiAccount,
  mdiAccountCircle,
  mdiAccountGroup,
  mdiAccountGroupOutline,
  mdiAccountMultiple,
  mdiAccountPlus,
  mdiAlert,
  mdiAlertCircle,
  mdiAlertCircleOutline,
  mdiAlphaGBox,
  mdiArrowLeft,
  mdiArrowRight,
  mdiAutoFix,
  mdiBank,
  mdiBook,
  mdiBookmark,
  mdiBookmarkOutline,
  mdiBookmarkRemove,
  mdiBookMultiple,
  mdiBookOffOutline,
  mdiBookOpen,
  mdiBookOpenPageVariant,
  mdiBookOpenVariant,
  mdiBookSearch,
  mdiBookSearchOutline,
  mdiBookshelf,
  mdiBrain,
  mdiBriefcase,
  mdiCalendar,
  mdiCalendarRange,
  mdiCalendarStar,
  mdiCards,
  mdiCardsOutline,
  mdiCart,
  mdiChartBar,
  mdiChartBellCurveCumulative,
  mdiChartLine,
  mdiCheck,
  mdiCheckCircle,
  mdiCheckCircleOutline,
  mdiChevronDown,
  mdiChevronLeft,
  mdiChevronRight,
  mdiChevronUp,
  mdiCircle,
  mdiCircleSmall,
  mdiClockDigital,
  mdiClockFast,
  mdiClockOutline,
  mdiClose,
  mdiCloseCircle,
  mdiCloseCircleOutline,
  mdiCommentOutline,
  mdiCommentText,
  mdiCommentTextOutline,
  mdiCompass,
  mdiCompassOutline,
  mdiDelete,
  mdiDiamondStone,
  mdiDomain,
  mdiEarth,
  mdiEmoticon,
  mdiEmoticonHappy,
  mdiEmoticonSadOutline,
  mdiEye,
  mdiEyeOff,
  mdiFeather,
  mdiFileDocument,
  mdiFileDocumentOutline,
  mdiFilter,
  mdiFilterRemove,
  mdiFire,
  mdiFlagCheckered,
  mdiFormatQuoteOpen,
  mdiFruitCherries,
  mdiGhost,
  mdiGithub,
  mdiGoogle,
  mdiHeart,
  mdiHeartOutline,
  mdiHeartPulse,
  mdiHelpCircleOutline,
  mdiHome,
  mdiImageFrame,
  mdiInformation,
  mdiInformationOutline,
  mdiLeaf,
  mdiLibrary,
  mdiLightningBolt,
  mdiLinkedin,
  mdiLinkVariant,
  mdiLogin,
  mdiLogout,
  mdiMagnify,
  mdiMagnifyRemoveOutline,
  mdiMagnifyScan,
  mdiMapMarker,
  mdiMenu,
  mdiMenuDown,
  mdiOpenInNew,
  mdiPencil,
  mdiPuzzle,
  mdiRefresh,
  mdiRocketLaunch,
  mdiRuler,
  mdiSchoolOutline,
  mdiShape,
  mdiShieldCrown,
  mdiShieldStar,
  mdiSlotMachine,
  mdiSnowflake,
  mdiSnowflakeVariant,
  mdiSofa,
  mdiSortAscending,
  mdiSortDescending,
  mdiStar,
  mdiStarCircle,
  mdiStarFourPoints,
  mdiStarHalfFull,
  mdiStarOffOutline,
  mdiStarOutline,
  mdiStarShooting,
  mdiTimelineOutline,
  mdiTranslate,
  mdiTreasureChest,
  mdiTrendingDown,
  mdiTrendingUp,
  mdiTrophy,
  mdiViewDashboard,
  mdiViewList,
  mdiWeatherNight,
  mdiWeatherSunny,
  mdiWeb,
  mdiWikipedia,
} from '@mdi/js'

export const mdiIconMap: Record<string, string> = {
  'mdi-account': mdiAccount,
  'mdi-account-circle': mdiAccountCircle,
  'mdi-account-group': mdiAccountGroup,
  'mdi-account-group-outline': mdiAccountGroupOutline,
  'mdi-account-multiple': mdiAccountMultiple,
  'mdi-account-plus': mdiAccountPlus,
  'mdi-alert': mdiAlert,
  'mdi-alert-circle': mdiAlertCircle,
  'mdi-alert-circle-outline': mdiAlertCircleOutline,
  'mdi-alpha-g-box': mdiAlphaGBox,
  'mdi-arrow-left': mdiArrowLeft,
  'mdi-arrow-right': mdiArrowRight,
  'mdi-auto-fix': mdiAutoFix,
  'mdi-bank': mdiBank,
  'mdi-book': mdiBook,
  'mdi-book-multiple': mdiBookMultiple,
  'mdi-book-off-outline': mdiBookOffOutline,
  'mdi-book-open': mdiBookOpen,
  'mdi-book-open-page-variant': mdiBookOpenPageVariant,
  'mdi-book-open-variant': mdiBookOpenVariant,
  'mdi-book-search': mdiBookSearch,
  'mdi-book-search-outline': mdiBookSearchOutline,
  'mdi-bookmark': mdiBookmark,
  'mdi-bookmark-outline': mdiBookmarkOutline,
  'mdi-bookmark-remove': mdiBookmarkRemove,
  'mdi-bookshelf': mdiBookshelf,
  'mdi-brain': mdiBrain,
  'mdi-briefcase': mdiBriefcase,
  'mdi-calendar': mdiCalendar,
  'mdi-calendar-range': mdiCalendarRange,
  'mdi-calendar-star': mdiCalendarStar,
  'mdi-cards': mdiCards,
  'mdi-cards-outline': mdiCardsOutline,
  'mdi-cart': mdiCart,
  'mdi-chart-bar': mdiChartBar,
  'mdi-chart-bell-curve-cumulative': mdiChartBellCurveCumulative,
  'mdi-chart-line': mdiChartLine,
  'mdi-check': mdiCheck,
  'mdi-check-circle': mdiCheckCircle,
  'mdi-check-circle-outline': mdiCheckCircleOutline,
  'mdi-chevron-down': mdiChevronDown,
  'mdi-chevron-left': mdiChevronLeft,
  'mdi-chevron-right': mdiChevronRight,
  'mdi-chevron-up': mdiChevronUp,
  'mdi-circle': mdiCircle,
  'mdi-circle-small': mdiCircleSmall,
  'mdi-clock-digital': mdiClockDigital,
  'mdi-clock-fast': mdiClockFast,
  'mdi-clock-outline': mdiClockOutline,
  'mdi-close': mdiClose,
  'mdi-close-circle': mdiCloseCircle,
  'mdi-close-circle-outline': mdiCloseCircleOutline,
  'mdi-comment-outline': mdiCommentOutline,
  'mdi-comment-text': mdiCommentText,
  'mdi-comment-text-outline': mdiCommentTextOutline,
  'mdi-compass': mdiCompass,
  'mdi-compass-outline': mdiCompassOutline,
  'mdi-delete': mdiDelete,
  'mdi-diamond-stone': mdiDiamondStone,
  'mdi-domain': mdiDomain,
  'mdi-earth': mdiEarth,
  'mdi-emoticon': mdiEmoticon,
  'mdi-emoticon-happy': mdiEmoticonHappy,
  'mdi-emoticon-sad-outline': mdiEmoticonSadOutline,
  'mdi-eye': mdiEye,
  'mdi-eye-off': mdiEyeOff,
  'mdi-feather': mdiFeather,
  'mdi-file-document': mdiFileDocument,
  'mdi-file-document-outline': mdiFileDocumentOutline,
  'mdi-filter': mdiFilter,
  'mdi-filter-remove': mdiFilterRemove,
  'mdi-fire': mdiFire,
  'mdi-flag-checkered': mdiFlagCheckered,
  'mdi-format-quote-open': mdiFormatQuoteOpen,
  'mdi-fruit-cherries': mdiFruitCherries,
  'mdi-ghost': mdiGhost,
  'mdi-github': mdiGithub,
  'mdi-google': mdiGoogle,
  'mdi-heart': mdiHeart,
  'mdi-heart-outline': mdiHeartOutline,
  'mdi-heart-pulse': mdiHeartPulse,
  'mdi-help-circle-outline': mdiHelpCircleOutline,
  'mdi-home': mdiHome,
  'mdi-image-frame': mdiImageFrame,
  'mdi-information': mdiInformation,
  'mdi-information-outline': mdiInformationOutline,
  'mdi-leaf': mdiLeaf,
  'mdi-library': mdiLibrary,
  'mdi-lightning-bolt': mdiLightningBolt,
  'mdi-link-variant': mdiLinkVariant,
  'mdi-linkedin': mdiLinkedin,
  'mdi-login': mdiLogin,
  'mdi-logout': mdiLogout,
  'mdi-magnify': mdiMagnify,
  'mdi-magnify-remove-outline': mdiMagnifyRemoveOutline,
  'mdi-magnify-scan': mdiMagnifyScan,
  'mdi-map-marker': mdiMapMarker,
  'mdi-menu': mdiMenu,
  'mdi-menu-down': mdiMenuDown,
  'mdi-open-in-new': mdiOpenInNew,
  'mdi-pencil': mdiPencil,
  'mdi-puzzle': mdiPuzzle,
  'mdi-refresh': mdiRefresh,
  'mdi-rocket-launch': mdiRocketLaunch,
  'mdi-ruler': mdiRuler,
  'mdi-school-outline': mdiSchoolOutline,
  'mdi-shape': mdiShape,
  'mdi-shield-crown': mdiShieldCrown,
  'mdi-shield-star': mdiShieldStar,
  'mdi-slot-machine': mdiSlotMachine,
  'mdi-snowflake': mdiSnowflake,
  'mdi-snowflake-variant': mdiSnowflakeVariant,
  'mdi-sofa': mdiSofa,
  'mdi-sort-ascending': mdiSortAscending,
  'mdi-sort-descending': mdiSortDescending,
  'mdi-star': mdiStar,
  'mdi-star-circle': mdiStarCircle,
  'mdi-star-four-points': mdiStarFourPoints,
  'mdi-star-half-full': mdiStarHalfFull,
  'mdi-star-off-outline': mdiStarOffOutline,
  'mdi-star-outline': mdiStarOutline,
  'mdi-star-shooting': mdiStarShooting,
  'mdi-timeline-outline': mdiTimelineOutline,
  'mdi-translate': mdiTranslate,
  'mdi-treasure-chest': mdiTreasureChest,
  'mdi-trending-down': mdiTrendingDown,
  'mdi-trending-up': mdiTrendingUp,
  'mdi-trophy': mdiTrophy,
  'mdi-view-dashboard': mdiViewDashboard,
  'mdi-view-list': mdiViewList,
  'mdi-weather-night': mdiWeatherNight,
  'mdi-weather-sunny': mdiWeatherSunny,
  'mdi-web': mdiWeb,
  'mdi-wikipedia': mdiWikipedia,
}
